Fix javadoc deployment
Failed because:
```
Error: Request failed with status code 400
    at createError (/home/runner/work/_actions/actions/deploy-pages/main/webpack:/deploy-pages/node_modules/axios/lib/core/createError.js:16:1)
    at settle (/home/runner/work/_actions/actions/deploy-pages/main/webpack:/deploy-pages/node_modules/axios/lib/core/settle.js:17:1)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/actions/deploy-pages/main/webpack:/deploy-pages/node_modules/axios/lib/adapters/http.js:293:1)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```